Args=--initialize-at-run-time=net.sourceforge.plantuml \
    --initialize-at-run-time=net.atmp \
    --initialize-at-run-time=java.awt \
    --initialize-at-run-time=java.awt.image \
    --initialize-at-run-time=java.awt.font \
    --initialize-at-run-time=java.awt.geom \
    --initialize-at-run-time=sun.java2d \
    --initialize-at-run-time=sun.awt
